version: '3.8'

services:

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "3000:3000"
    restart: unless-stopped

  customer-service:
    build:
      context: ./customer-services
      dockerfile: Dockerfile
    container_name: customer-service
    ports:
      - "3005:3005"
    depends_on:
      - api-gateway
    restart: unless-stopped

  inventory-service:
    build:
      context: ./inventory-services
      dockerfile: Dockerfile
    container_name: inventory-service
    ports:
      - "3004:3004"
    depends_on:
      - api-gateway
    restart: unless-stopped

  menu-service:
    build:
      context: ./menu-services
      dockerfile: Dockerfile
    container_name: menu-service
    ports:
      - "3001:3001"
    depends_on:
      - api-gateway
    restart: unless-stopped

  order-service:
    build:
      context: ./order-services
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "3002:3002"
    depends_on:
      - api-gateway
    restart: unless-stopped

  payment-service:
    build:
      context: ./payment-services
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "3003:3003"
    depends_on:
      - api-gateway
    restart: unless-stopped

